// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDITFVel0HKOdNWL4TPKISq9y0DFl7Ck04',
    appId: '1:682868386904:web:1367e6a811cb29ac22ee2d',
    messagingSenderId: '682868386904',
    projectId: 'flutter-notes-app-aadf7',
    authDomain: 'flutter-notes-app-aadf7.firebaseapp.com',
    storageBucket: 'flutter-notes-app-aadf7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBojRXvwwxBjNX-f6HfRE8qcTCwRNRRnY',
    appId: '1:682868386904:android:b55297d8cdea436522ee2d',
    messagingSenderId: '682868386904',
    projectId: 'flutter-notes-app-aadf7',
    storageBucket: 'flutter-notes-app-aadf7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlYrrH3lRLRDf_EIGETLjCM31Z3IyR1iI',
    appId: '1:682868386904:ios:30a5f3731495842a22ee2d',
    messagingSenderId: '682868386904',
    projectId: 'flutter-notes-app-aadf7',
    storageBucket: 'flutter-notes-app-aadf7.appspot.com',
    iosClientId: '682868386904-nj4km75vfq1u900i85cs9vbhudmpt1c2.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterNotesApp',
  );
}
